from __future__ import annotations

import json
from pathlib import Path

from .models import SYSTEM_COLLECTIONS


def rebuild_system_metadata(games_dir: Path, system: str) -> None:
    installed_games = _installed_games(games_dir, system)
    metadata_path = _metadata_path(games_dir, system)
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    lines = _collection_header(system)
    for install_dir, receipt in installed_games:
        lines.extend(_game_metadata(install_dir, receipt))
    _atomic_write_text(metadata_path, "\n".join(lines) + "\n")


def _installed_games(games_dir: Path, system: str) -> list[tuple[Path, dict]]:
    install_root = games_dir / "roms" / system / "romstore"
    if not install_root.is_dir():
        return []
    games: list[tuple[Path, dict]] = []
    for receipt_path in sorted(install_root.glob("*/receipt.json")):
        receipt = _valid_receipt(receipt_path, system)
        if receipt:
            games.append((receipt_path.parent, receipt))
    return games


def _valid_receipt(path: Path, system: str) -> dict | None:
    try:
        receipt = json.loads(path.read_text(encoding="utf-8"))
        primary_file = path.parent / receipt["primary_file"]
    except (OSError, ValueError, KeyError, TypeError):
        return None
    return receipt if receipt.get("system") == system and primary_file.is_file() else None


def _metadata_path(games_dir: Path, system: str) -> Path:
    return (
        games_dir
        / "config"
        / "pegasus-frontend"
        / "metafiles"
        / f"romstore-{system}.metadata.pegasus.txt"
    )


def _collection_header(system: str) -> list[str]:
    return [
        "# Generated by KonsolenDocker ROM Store. Manual edits will be replaced.",
        f"collection: {SYSTEM_COLLECTIONS[system]}",
        f"shortname: {system}",
    ]


def _game_metadata(install_dir: Path, receipt: dict) -> list[str]:
    primary_file = install_dir / receipt["primary_file"]
    lines = [
        "",
        f"game: {_metadata_value(receipt.get('title', primary_file.stem))}",
        f"file: {primary_file}",
    ]
    if receipt.get("developer"):
        lines.append(f"developer: {_metadata_value(receipt['developer'])}")
    description = receipt.get("description") or _default_description(receipt)
    lines.extend(
        [
            f"description: {_metadata_value(description)}",
            f"tags: {_metadata_value(receipt.get('kind', 'Homebrew'))}, Homebrew",
        ]
    )
    cover_file = install_dir / receipt.get("cover_file", "")
    if cover_file.is_file():
        lines.append(f"assets.box_front: {cover_file}")
    return lines


def _default_description(receipt: dict) -> str:
    return f"{receipt.get('kind', 'Homebrew')} – {receipt.get('provider', 'ROM Store')}"


def _metadata_value(value: object) -> str:
    return str(value).replace("\\", "\\\\").replace("\r", " ").replace("\n", "\\n").strip()


def _atomic_write_text(path: Path, content: str) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)
